version: "3"

services:
  database:
    restart: always
    image: mysql:latest
    container_name: mysqlserver
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: management
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - management:/var/lib/mysql
volumes:
  management: